export const PRESETS = [
  {
    id: "forget-status",
    name: "Forget Status",
    category: "editorial",
    badge: "Editorial",
    tags: ["Bold", "Kinetic"],
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    italic: false,
    weight: 900,
    color: "#38bdf8",
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 0 20px rgba(56,189,248,0.7), 0 2px 10px rgba(0,0,0,0.95)",
    letterSpacing: "0.03em",
    case: "uppercase",
    animation: "pop",
    styleType: "dual-tone-kinetic",
  },
  {
    id: "focus-deeply",
    name: "Focus Deeply",
    category: "swiss",
    badge: "Editorial",
    tags: ["Bold", "Kinetic"],
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#facc15",
    weight: 900,
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 4px 16px rgba(0,0,0,0.95)",
    letterSpacing: "0.02em",
    case: "uppercase",
    animation: "pop",
    styleType: "swiss-duo",
  },
  {
    id: "the-big-red",
    name: "The Big Red",
    category: "editorial",
    badge: "New",
    tags: ["Bold", "Kinetic"],
    font: "'Cinzel', 'Playfair Display', Georgia, serif",
    color: "#ef4444",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.65)",
    shadow: "0 0 25px rgba(239,68,68,0.85), 0 2px 10px rgba(0,0,0,0.95)",
    letterSpacing: "0.06em",
    case: "uppercase",
    weight: 900,
    italic: false,
    animation: "pop",
    styleType: "big-red",
  },
  {
    id: "the-little-things",
    name: "The Little Things",
    category: "handwritten",
    badge: "New",
    tags: ["Kinetic", "Handwritten"],
    font: "'Caveat', cursive, sans-serif",
    color: "#facc15",
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 2px 12px rgba(0,0,0,0.95)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 700,
    italic: false,
    styleType: "highlighter-doodle",
  },
  {
    id: "archives",
    name: "Archives",
    category: "handwritten",
    badge: "New",
    tags: ["Kinetic", "Handwritten"],
    font: "'Caveat', cursive, serif",
    color: "#fde047",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.5)",
    shadow: "0 2px 14px rgba(0,0,0,0.95)",
    letterSpacing: "0.04em",
    case: "none",
    animation: "fade",
    weight: 700,
    italic: false,
    styleType: "vintage-flourish",
  },
  {
    id: "blockbuster",
    name: "Blockbuster",
    category: "cinematic",
    badge: "New",
    tags: ["Kinetic", "Cinematic"],
    font: "'Anton', 'Plus Jakarta Sans', sans-serif",
    color: "#ffffff",
    secondaryColor: "#ef4444",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.55)",
    shadow: "0 0 25px rgba(239,68,68,0.95), 0 2px 10px rgba(0,0,0,0.95)",
    letterSpacing: "0.05em",
    case: "uppercase",
    animation: "pop",
    weight: 900,
    italic: false,
    styleType: "blockbuster-neon",
  },
  {
    id: "beast",
    name: "Beast Style",
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#facc15",
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 4px 14px rgba(0,0,0,0.95)",
    letterSpacing: "0.02em",
    case: "uppercase",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "karaoke",
    name: "Karaoke Smooth",
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#facc15",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.65)",
    shadow: "0 2px 10px rgba(0,0,0,0.9)",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 800,
    italic: false,
  },
  {
    id: "minimal-bold",
    name: "Minimal Bold",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.6)",
    shadow: "0 1px 4px rgba(0,0,0,0.3)",
    letterSpacing: "0.04em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "hype-amber",
    name: "Hype Amber",
    font: "Inter, system-ui, sans-serif",
    color: "#09090b",
    stroke: "transparent",
    bg: "#facc15",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "clean-mono",
    name: "Clean Mono",
    font: "'JetBrains Mono', monospace",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(24,24,27,0.85)",
    shadow: "none",
    letterSpacing: "0",
    case: "none",
    animation: "fade",
    weight: 500,
    italic: false,
  },
  {
    id: "hormozi",
    name: "Hormozi",
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#4ade80",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.75)",
    shadow: "0 2px 12px rgba(0,0,0,0.95)",
    letterSpacing: "0.03em",
    case: "uppercase",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "grit",
    name: "Grit",
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#facc15",
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 0 20px rgba(250,204,21,0.6), 0 2px 12px rgba(0,0,0,0.95)",
    letterSpacing: "0.06em",
    case: "uppercase",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "prism",
    name: "Prism",
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#a78bfa",
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 0 20px rgba(167,139,250,0.7), 0 2px 12px rgba(0,0,0,0.95)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "slide",
    weight: 800,
    italic: false,
  },
  {
    id: "glitch",
    name: "Glitch",
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#22d3ee",
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 0 20px rgba(34,211,238,0.7), 0 2px 12px rgba(0,0,0,0.95)",
    letterSpacing: "0.01em",
    case: "uppercase",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "word-pop",
    name: "Word Pop",
    font: "'Plus Jakarta Sans', 'Inter', sans-serif",
    color: "#facc15",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.6)",
    shadow: "0 2px 12px rgba(0,0,0,0.95)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "bubble",
    name: "Bubble",
    font: "Inter, system-ui, sans-serif",
    color: "#000000",
    stroke: "transparent",
    bg: "#facc15",
    shadow: "0 4px 12px rgba(250,204,21,0.3)",
    letterSpacing: "0.01em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "deep-glow",
    name: "Deep Glow",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "rgba(250,204,21,0.6)",
    bg: "transparent",
    shadow: "0 0 30px rgba(250,204,21,0.25)",
    letterSpacing: "0.04em",
    case: "none",
    animation: "fade",
    weight: 800,
    italic: false,
  },
  {
    id: "highlighted",
    name: "Highlighted",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "#000000",
    bg: "rgba(250,204,21,0.2)",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 700,
    italic: false,
  },
  {
    id: "liquid-glass",
    name: "Liquid Glass",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(255,255,255,0.08)",
    shadow: "none",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  {
    id: "delhi",
    name: "Delhi",
    font: "Inter, system-ui, sans-serif",
    color: "#facc15",
    stroke: "#000000",
    bg: "transparent",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "neon-cyan",
    name: "Neon Cyan",
    font: "Inter, system-ui, sans-serif",
    color: "#06b6d4",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 25px rgba(6,182,212,0.3)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "neon-pink",
    name: "Neon Pink",
    font: "Inter, system-ui, sans-serif",
    color: "#ec4899",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 25px rgba(236,72,153,0.3)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 900,
    italic: false,
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    font: "'Courier New', monospace",
    color: "#facc15",
    stroke: "#000000",
    bg: "rgba(0,0,0,0.7)",
    shadow: "0 0 15px rgba(250,204,21,0.2)",
    letterSpacing: "0.08em",
    case: "uppercase",
    animation: "slide",
    weight: 700,
    italic: false,
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    font: "Inter, system-ui, sans-serif",
    color: "#e879f9",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(232,121,249,0.2)",
    letterSpacing: "0.05em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "vintage-film",
    name: "Vintage Film",
    font: "'Georgia', serif",
    color: "#fbbf24",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.6)",
    shadow: "none",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: true,
  },
  {
    id: "typewriter",
    name: "Typewriter",
    font: "'Courier New', monospace",
    color: "#e4e4e7",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.5)",
    shadow: "none",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 500,
    italic: false,
  },
  {
    id: "gradient-gold",
    name: "Gradient Gold",
    font: "Inter, system-ui, sans-serif",
    color: "#fbbf24",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.45)",
    shadow: "0 1px 6px rgba(0,0,0,0.3)",
    letterSpacing: "0.03em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "midnight",
    name: "Midnight",
    font: "Inter, system-ui, sans-serif",
    color: "#94a3b8",
    stroke: "#000000",
    bg: "rgba(0,0,0,0.5)",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  {
    id: "tangerine",
    name: "Tangerine",
    font: "Inter, system-ui, sans-serif",
    color: "#fb923c",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(251,146,60,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "mint",
    name: "Mint",
    font: "Inter, system-ui, sans-serif",
    color: "#34d399",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(52,211,153,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "ruby",
    name: "Ruby Red",
    font: "Inter, system-ui, sans-serif",
    color: "#fb7185",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(251,113,133,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "sunset",
    name: "Sunset",
    font: "Inter, system-ui, sans-serif",
    color: "#fdba74",
    stroke: "#000000",
    bg: "rgba(0,0,0,0.4)",
    shadow: "0 0 20px rgba(253,186,116,0.15)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "ocean",
    name: "Ocean Blue",
    font: "Inter, system-ui, sans-serif",
    color: "#60a5fa",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(96,165,250,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "forest",
    name: "Forest Green",
    font: "Inter, system-ui, sans-serif",
    color: "#4ade80",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(74,222,128,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 800,
    italic: false,
  },
  {
    id: "royal",
    name: "Royal Purple",
    font: "Inter, system-ui, sans-serif",
    color: "#c084fc",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(192,132,252,0.2)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 800,
    italic: false,
  },
  {
    id: "crystal",
    name: "Crystal Clear",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(255,255,255,0.06)",
    shadow: "none",
    letterSpacing: "0.04em",
    case: "none",
    animation: "fade",
    weight: 500,
    italic: false,
  },
  {
    id: "paper",
    name: "Paper Cutout",
    font: "'Georgia', serif",
    color: "#292524",
    stroke: "transparent",
    bg: "#fef3c7",
    shadow: "0 1px 3px rgba(0,0,0,0.1)",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 700,
    italic: false,
  },
  {
    id: "cinematic",
    name: "Cinematic",
    font: "Inter, system-ui, sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.55)",
    shadow: "0 1px 4px rgba(0,0,0,0.2)",
    letterSpacing: "0.06em",
    case: "uppercase",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  // ── Pinterest Aesthetic Presets ──
  {
    id: "editorial-serif",
    name: "Editorial Serif",
    font: "'Playfair Display', serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.4)",
    shadow: "none",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 500,
    italic: false,
  },
  {
    id: "vogue-italic",
    name: "Vogue Italic",
    font: "'Playfair Display', serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "transparent",
    shadow: "0 2px 12px rgba(0,0,0,0.3)",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 400,
    italic: true,
  },
  {
    id: "instruments",
    name: "Instruments",
    font: "'Instrument Serif', serif",
    color: "#fafafa",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.35)",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 400,
    italic: false,
  },
  {
    id: "fraunces-super",
    name: "Fraunces",
    font: "'Fraunces', serif",
    color: "#fbbf24",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(251,191,36,0.15)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "pop",
    weight: 700,
    italic: false,
  },
  {
    id: "old-money",
    name: "Old Money",
    font: "'Playfair Display', serif",
    color: "#C9A96E",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 20px rgba(201,169,110,0.12)",
    letterSpacing: "0.04em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  {
    id: "modern-magazine",
    name: "Modern Magazine",
    font: "'DM Sans', sans-serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.5)",
    shadow: "0 1px 4px rgba(0,0,0,0.2)",
    letterSpacing: "0.08em",
    case: "uppercase",
    animation: "fade",
    weight: 700,
    italic: false,
  },
  {
    id: "aesthetic-serifs",
    name: "Aesthetic Serifs",
    font: "'Cormorant Garamond', serif",
    color: "#292524",
    stroke: "transparent",
    bg: "rgba(245,240,235,0.9)",
    shadow: "none",
    letterSpacing: "0.01em",
    case: "none",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  {
    id: "roman-engraved",
    name: "Roman Engraved",
    font: "'Cinzel', serif",
    color: "#facc15",
    stroke: "#000000",
    bg: "transparent",
    shadow: "0 0 15px rgba(250,204,21,0.1)",
    letterSpacing: "0.06em",
    case: "uppercase",
    animation: "fade",
    weight: 600,
    italic: false,
  },
  {
    id: "album-cover",
    name: "Album Cover",
    font: "'Instrument Serif', serif",
    color: "#ffffff",
    stroke: "transparent",
    bg: "rgba(0,0,0,0.45)",
    shadow: "0 2px 8px rgba(0,0,0,0.3)",
    letterSpacing: "0.12em",
    case: "uppercase",
    animation: "fade",
    weight: 400,
    italic: false,
  },
  {
    id: "pinterest-mood",
    name: "Pinterest Mood",
    font: "'Playfair Display', serif",
    color: "#1a1a1a",
    stroke: "transparent",
    bg: "rgba(250,245,240,0.92)",
    shadow: "0 1px 6px rgba(0,0,0,0.06)",
    letterSpacing: "0.02em",
    case: "none",
    animation: "fade",
    weight: 400,
    italic: true,
  },
];
